// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebApplication.DataAccess;

#nullable disable

namespace TestWebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestWebApplication.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Familly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb778e"),
                            Address = "Shahmirzad",
                            BirthDay = new DateTime(1988, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Familly = "Shokri",
                            Name = "Navid"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-11c5-4c4e-99cf-6e9f5fcb778e"),
                            Address = "Shahmirzad",
                            BirthDay = new DateTime(1986, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Familly = "Shokri",
                            Name = "Ali"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb779e"),
                            Address = "Semnan",
                            BirthDay = new DateTime(1988, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Familly = "Salavati",
                            Name = "Saeed"
                        });
                });

            modelBuilder.Entity("TestWebApplication.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5312d91-10c5-4c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb778e"),
                            Title = "SWE"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-18c5-4c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb778e"),
                            Title = "Welding"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-20c5-4c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb778e"),
                            Title = "Coaching"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-12c5-4c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-11c5-4c4e-99cf-6e9f5fcb778e"),
                            Title = "Construction"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-15c5-4c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-11c5-4c4e-99cf-6e9f5fcb778e"),
                            Title = "Communication"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-00c5-3c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-11c5-4c4e-99cf-6e9f5fcb778e"),
                            Title = "Coaching"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-45c5-4c4e-99cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb779e"),
                            Title = "Mechanics"
                        },
                        new
                        {
                            Id = new Guid("c5312d91-00c5-4c4e-10cf-6e9f5fcb778e"),
                            PersonId = new Guid("c5312d91-00c5-4c4e-99cf-6e9f5fcb779e"),
                            Title = "Accounting"
                        });
                });

            modelBuilder.Entity("TestWebApplication.Models.Skill", b =>
                {
                    b.HasOne("TestWebApplication.Models.Person", null)
                        .WithMany("Skills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestWebApplication.Models.Person", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
